const OPEN_ADD_MOVIE_MODAL = "movies-app/modals/OPEN_ADD_MOVIE_MODAL";
const OPEN_EDIT_MOVIE_MODAL = "movies-app/modals/OPEN_EDIT_MOVIE_MODAL";
const OPEN_DELETE_MOVIE_MODAL = "movies-app/modals/OPEN_DELETE_MOVIE_MODAL";
const CLOSE_MOVIE_MODAL = "movies-app/modals/CLOSE_MOVIE_MODAL";

export {
  OPEN_ADD_MOVIE_MODAL,
  OPEN_EDIT_MOVIE_MODAL,
  OPEN_DELETE_MOVIE_MODAL,
  CLOSE_MOVIE_MODAL,
};
