const FETCH_MOVIES_START = "movies-app/movies/FETCH_MOVIES_START";
const FETCH_MOVIES_REQUEST = "movies-app/movies/FETCH_MOVIES_REQUEST";
const FETCH_MOVIES_SUCCESS = "movies-app/movies/FETCH_MOVIES_SUCCESS";
const FETCH_MOVIES_FAILURE = "movies-app/movies/FETCH_MOVIES_FAILURE";

const POST_MOVIE_START = "movies-app/movies/POST_MOVIE_START";
const POST_MOVIE_REQUEST = "movies-app/movies/POST_MOVIE_REQUEST";
const POST_MOVIE_SUCCESS = "movies-app/movies/POST_MOVIE_SUCCESS";
const POST_MOVIE_FAILURE = "movies-app/movies/POST_MOVIE_FAILURE";

const DELETE_MOVIE_START = "movies-app/movies/DELETE_MOVIE_START";
const DELETE_MOVIE_REQUEST = "movies-app/movies/DELETE_MOVIE_REQUEST";
const DELETE_MOVIE_SUCCESS = "movies-app/movies/DELETE_MOVIE_SUCCESS";
const DELETE_MOVIE_FAILURE = "movies-app/movies/DELETE_MOVIE_FAILURE";

const EDIT_MOVIE_START = "movies-app/movies/EDIT_MOVIE_START";
const EDIT_MOVIE_REQUEST = "movies-app/movies/EDIT_MOVIE_REQUEST";
const EDIT_MOVIE_SUCCESS = "movies-app/movies/EDIT_MOVIE_SUCCESS";
const EDIT_MOVIE_FAILURE = "movies-app/movies/EDIT_MOVIE_FAILURE";

const SET_GENRE = "movies-app/movies/SET_GENRE";
const SELECT_MOVIE = "movies-app/movies/SELECT_MOVIE";
const SELECT_SORT_BY = "movies-app/movies/SELECT_SORT_BY";
const SUBMIT_SEARCH = "movies-app/movies/SUBMIT_SEARCH";

export {
  FETCH_MOVIES_START,
  FETCH_MOVIES_REQUEST,
  FETCH_MOVIES_SUCCESS,
  FETCH_MOVIES_FAILURE,
  POST_MOVIE_START,
  POST_MOVIE_REQUEST,
  POST_MOVIE_SUCCESS,
  POST_MOVIE_FAILURE,
  DELETE_MOVIE_START,
  DELETE_MOVIE_REQUEST,
  DELETE_MOVIE_SUCCESS,
  DELETE_MOVIE_FAILURE,
  EDIT_MOVIE_START,
  EDIT_MOVIE_REQUEST,
  EDIT_MOVIE_SUCCESS,
  EDIT_MOVIE_FAILURE,
  SET_GENRE,
  SELECT_MOVIE,
  SELECT_SORT_BY,
  SUBMIT_SEARCH,
};
